# Generated by Django 4.0.4 on 2022-05-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_servicios_homepagecarouselimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='servicio_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='Texto',
        ),
        migrations.DeleteModel(
            name='HomePageCarouselImages',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
