# Generated by Django 4.0.4 on 2022-05-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_servicios_page_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Texto',
            new_name='body',
        ),
    ]
