# Generated by Django 4.0.4 on 2022-05-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0005_rename_texto_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_image1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
