# Generated by Django 4.0.4 on 2022-05-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_banner_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_image1',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='Texto',
        ),
    ]
