# Generated by Django 4.0.4 on 2022-05-19 02:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_banner_image1_homepage_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Texto',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
