# Generated by Django 4.0.4 on 2022-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Imagen',
            new_name='Imagen_de_bienvenida',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Texto',
            new_name='Separador_de_servicios',
        ),
        migrations.AddField(
            model_name='homepage',
            name='Texto_de_bienvenida',
            field=models.TextField(default=''),
        ),
    ]
