# Generated by Django 4.0.4 on 2022-05-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_imagen_homepage_imagen_de_bienvenida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Separador_de_anuncios',
            field=models.TextField(default=''),
        ),
    ]
