# Generated by Django 4.0.4 on 2022-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_serviciospage_serviciosimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciospage',
            name='category',
            field=models.TextField(choices=[('HG', 'Hogar'), ('ELCTR', 'Electricidad')], default='HG', max_length=5),
        ),
    ]
