# Generated by Django 4.0.4 on 2022-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_serviciospage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='Texto_slide',
            field=models.TextField(default='test title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='Titulo_slide',
            field=models.TextField(default='test txt'),
            preserve_default=False,
        ),
    ]
