# Generated by Django 4.0.4 on 2022-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepagecarouselimages_texto_slide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='Texto_slide',
            field=models.TextField(default='test title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='Titulo_slide',
            field=models.TextField(default='test txt'),
            preserve_default=False,
        ),
    ]
