# Generated by Django 4.0.4 on 2022-05-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0020_homepage_logo_barra_de_navegación_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Separador_de_servicios',
            new_name='Separador_anuncios',
        ),
        migrations.AddField(
            model_name='homepage',
            name='Imagen_der',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Imagen_izq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Separador_servicios',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Texto_der',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Texto_izq',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Titulo_der',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Titulo_izq',
            field=models.TextField(default=''),
        ),
    ]
