# Generated by Django 4.0.4 on 2022-05-23 01:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0025_serviciospage_titulo_trabajos_hechos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConocenosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Navegación_1', models.TextField(default='')),
                ('Navegación_2', models.TextField(default='')),
                ('Navegación_3', models.TextField(default='')),
                ('Navegación_4', models.TextField(default='')),
                ('Texto_del_cuadro', models.TextField(default='')),
                ('Título_del_mapa', models.TextField(default='')),
                ('Título_principal', models.TextField(default='')),
                ('Texto_principal', models.TextField(default='')),
                ('Primer_título', models.TextField(default='')),
                ('Texto_1er_título', models.TextField(default='')),
                ('Segundo_título', models.TextField(default='')),
                ('Texto_2ndo_título', models.TextField(default='')),
                ('Tercer_título', models.TextField(default='')),
                ('Texto_3er_título', models.TextField(default='')),
                ('Separador_colab', models.TextField(default='')),
                ('Texto1', models.TextField(default='')),
                ('Texto2', models.TextField(blank=True, default='', null=True)),
                ('Logo_footer', models.TextField(default='')),
                ('Direccion_footer', models.TextField(default='')),
                ('enlacesTitulo', models.TextField(default='')),
                ('Enlace_1', models.TextField(default='')),
                ('Enlace_2', models.TextField(default='')),
                ('Enlace_3', models.TextField(default='')),
                ('tituloContacto', models.TextField(default='')),
                ('Enlace_4', models.TextField(default='')),
                ('Enlace_5', models.TextField(default='')),
                ('Enlace_6', models.TextField(default='')),
                ('Enlace_7', models.TextField(default='')),
                ('tituloRedes', models.TextField(default='')),
                ('Imagen_1er_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_2ndo_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_3er_título', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_RedSocial1_footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_RedSocial2_footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_en_el_cuadro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Direccion_footer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Enlace_7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Logo_RedSocial1_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Logo_RedSocial2_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Logo_footer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enlacesTitulo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tituloContacto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tituloRedes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Boton_cuadro_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Boton_cuadro_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Descripción_cuadro_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Descripción_cuadro_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Descripción_cuadro_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Direccion_footer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Enlace_7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Icono_cuadro_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Icono_cuadro_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Icono_cuadro_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Logo_RedSocial1_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Logo_RedSocial2_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Logo_footer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Título_cuadro_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Título_cuadro_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Título_cuadro_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Título_sección',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='enlacesTitulo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='tituloContacto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='tituloRedes',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='PreguntasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Navegación_1', models.TextField(default='')),
                ('Navegación_2', models.TextField(default='')),
                ('Navegación_3', models.TextField(default='')),
                ('Navegación_4', models.TextField(default='')),
                ('Título_principal', models.TextField(default='')),
                ('Texto_inicial', models.TextField(default='')),
                ('Logo_footer', models.TextField(default='')),
                ('Direccion_footer', models.TextField(default='')),
                ('enlacesTitulo', models.TextField(default='')),
                ('Enlace_1', models.TextField(default='')),
                ('Enlace_2', models.TextField(default='')),
                ('Enlace_3', models.TextField(default='')),
                ('tituloContacto', models.TextField(default='')),
                ('Enlace_4', models.TextField(default='')),
                ('Enlace_5', models.TextField(default='')),
                ('Enlace_6', models.TextField(default='')),
                ('Enlace_7', models.TextField(default='')),
                ('tituloRedes', models.TextField(default='')),
                ('Logo_RedSocial1_footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_RedSocial2_footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PlantPregunta',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(default='')),
                ('respuesta', models.TextField(default='')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_preguntas', to='home.preguntaspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Navegación_1', models.TextField(default='')),
                ('Navegación_2', models.TextField(default='')),
                ('Navegación_3', models.TextField(default='')),
                ('Navegación_4', models.TextField(default='')),
                ('Usuario_Red_Social_1', models.TextField(default='')),
                ('Usuario_Red_Social_2', models.TextField(default='')),
                ('Telefono_1', models.TextField(default='')),
                ('Telefono_2', models.TextField(default='')),
                ('Correo_electronico', models.TextField(default='')),
                ('Correo_electronico_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Red_Social_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Red_Social_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Telefono_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Imagen_Telefono_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConocenosPageSlider',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='home.conocenospage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
