# Generated by Django 4.0.4 on 2022-05-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_conocenospage_homepage_direccion_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='categ',
            field=models.TextField(choices=[('C1', 'Cuadro 1'), ('C2', 'Cuadro 2')], default='C1', max_length=3),
        ),
    ]
