# Generated by Django 4.0.4 on 2022-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_homepage_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciospage',
            name='category',
            field=models.TextField(choices=[('HG', 'Hogar'), ('ELCTR', 'Electricidad'), ('PAINT', 'Pintura'), ('BUILD', 'Construccion')], default='HG', max_length=5),
        ),
    ]
