# Generated by Django 4.0.4 on 2022-05-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0030_alter_serviciospage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Logo_RedSocial1_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Logo_RedSocial2_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Navegación_4',
            field=models.CharField(default='Contacto', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
    ]
