# Generated by Django 4.0.4 on 2022-05-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_contactpage_direccion_footer_contactpage_enlace_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentspage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
    ]
