# Generated by Django 4.0.4 on 2022-05-24 04:48

import django.core.validators
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_commentspage_navegación_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Separador_anuncios',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Separador_servicios',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Texto_de_bienvenida',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Texto_der',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Texto_izq',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Titulo_der',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Titulo_izq',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='Texto_slide',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='Titulo_slide',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Boton_cuadro_2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Boton_cuadro_3',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_1',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_3',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Titulo_trabajos_hechos',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Título_cuadro_1',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Título_cuadro_2',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Título_cuadro_3',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Título_sección',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(733)]),
        ),
    ]
