# Generated by Django 4.0.4 on 2022-05-24 05:12

import django.core.validators
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_homepage_separador_anuncios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto_del_cuadro',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Título_del_mapa',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_1',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_2',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_3',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
