# Generated by Django 4.0.4 on 2022-05-24 05:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_conocenospage_texto_del_cuadro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_1',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
