# Generated by Django 4.0.4 on 2022-05-24 06:23

import django.core.validators
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_serviciospage_descripción_cuadro_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conocenospage',
            name='Primer_título',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Segundo_título',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Separador_colab',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Tercer_título',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto1',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto2',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto_1er_título',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto_2ndo_título',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto_3er_título',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Texto_principal',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Título_principal',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Correo_electronico',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_1',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_2',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Usuario_Red_Social_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Usuario_Red_Social_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantpregunta',
            name='pregunta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantpregunta',
            name='respuesta',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Texto_inicial',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntaspage',
            name='Título_principal',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_1',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(280)]),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_2',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(130)]),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Descripción_cuadro_3',
            field=wagtail.core.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(130)]),
        ),
    ]
