# Generated by Django 4.0.4 on 2022-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_conocenospage_primer_título_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciospage',
            name='category',
            field=models.TextField(choices=[('Hogar', 'Hogar'), ('Electricidad', 'Electricidad'), ('Pintura', 'Pintura'), ('Contrucción', 'Construccion')], default='Hogar', max_length=12),
        ),
    ]
