# Generated by Django 4.0.4 on 2022-05-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_homepage_imagen_categoría_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciospage',
            name='category',
            field=models.TextField(choices=[('HOGAR', 'HOGAR'), ('ELECTRICIDAD', 'ELECTRICIDAD'), ('Pintura', 'Pintura'), ('CONSTRUCCIÓN', 'CONSTRUCCIÓN')], default='HOGAR', max_length=12),
        ),
    ]
