# Generated by Django 4.0.4 on 2022-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_serviciospage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AlterField(
            model_name='commentspage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AlterField(
            model_name='conocenospage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviciospage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
    ]
