# Generated by Django 4.0.4 on 2022-05-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0043_alter_commentspage_enlace_5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='Logo_barra_de_navegación',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Navegación_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Navegación_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Navegación_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Navegación_4',
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Navegación_1', models.CharField(default='Inicio', max_length=15)),
                ('Navegación_2', models.CharField(default='Servicios', max_length=15)),
                ('Navegación_3', models.CharField(default='Conócenos', max_length=15)),
                ('Navegación_4', models.CharField(default='Contáctanos', max_length=15)),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
