# Generated by Django 4.0.4 on 2022-05-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0044_remove_homepage_logo_barra_de_navegación_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='Logo_barra_de_navegación',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.DeleteModel(
            name='header',
        ),
    ]
