# Generated by Django 4.0.4 on 2022-05-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_commentpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentspagecarouselcomments',
            name='page',
        ),
        migrations.DeleteModel(
            name='CommentsPage',
        ),
        migrations.DeleteModel(
            name='CommentsPageCarouselComments',
        ),
    ]
