# Generated by Django 4.0.4 on 2022-05-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0047_remove_commentspagecarouselcomments_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpage',
            name='Direccion_footer',
            field=models.CharField(default='C. Pisperama 180-interior. 6, Vista Bella, 58090 Morelia, Mich.', max_length=100),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_1',
            field=models.CharField(default='Conócenos', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_2',
            field=models.CharField(default='Preguntas frecuentes', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_3',
            field=models.CharField(default='Comentarios', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_4',
            field=models.CharField(default='Contáctanos', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Enlace_7',
            field=models.CharField(default='grupolias@hotmail.com', max_length=40),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Image_EComments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Logo_RedSocial1_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Logo_RedSocial2_footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Logo_barra_de_navegación',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Logo_footer',
            field=models.CharField(default='Grupo LIAS', max_length=15),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=15),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=15),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=15),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=15),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Text_EComments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='enlacesTitulo',
            field=models.CharField(default='OTROS ENLACES', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='tituloContacto',
            field=models.CharField(default='CONTACTO', max_length=20),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='tituloRedes',
            field=models.CharField(default='SIGUENOS EN NUESTRAS REDES', max_length=30),
        ),
    ]
