# Generated by Django 4.0.4 on 2022-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_commentpage_direccion_footer_commentpage_enlace_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identificador', models.SlugField(allow_unicode=True, help_text='Nombre para identificar a esta categoria', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Categoria pregunta',
                'verbose_name_plural': 'Categoria preguntas',
                'ordering': ['nombre'],
            },
        ),
    ]
