# Generated by Django 4.0.4 on 2022-05-29 20:17

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_preguntascategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntascategory',
            name='identificador',
        ),
        migrations.AddField(
            model_name='plantpregunta',
            name='categoría',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.preguntascategory'),
        ),
        migrations.AddField(
            model_name='preguntascategory',
            name='Identificador',
            field=models.SlugField(allow_unicode=True, help_text='Nombre para identificar a esta categoria', null=True, verbose_name='Identificador'),
        ),
    ]
