# Generated by Django 4.0.4 on 2022-05-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_preguntaspage_categoría_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantpregunta',
            options={},
        ),
        migrations.RemoveField(
            model_name='plantpregunta',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='preguntaspage',
            name='categoría',
        ),
    ]
