# Generated by Django 4.0.4 on 2022-05-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_plantpregunta_options_plantpregunta_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantpregunta',
            name='categoría',
        ),
        migrations.AddField(
            model_name='plantpregunta',
            name='categoría',
            field=models.CharField(default='', max_length=40),
        ),
    ]
