# Generated by Django 4.0.4 on 2022-05-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0054_remove_plantpregunta_categoría_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navegación_1', models.CharField(default='Inicio', max_length=15)),
                ('Navegación_2', models.CharField(default='Servicios', max_length=15)),
                ('Navegación_3', models.CharField(default='Conócenos', max_length=15)),
                ('Navegación_4', models.CharField(default='Contáctanos', max_length=15)),
                ('Logo_barra_de_navegación', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
