# Generated by Django 4.0.4 on 2022-05-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('header_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.header')),
                ('body', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.header',),
        ),
    ]
