# Generated by Django 4.0.4 on 2022-05-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_delete_preguntascategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaspage',
            name='Texto_inicial',
        ),
    ]
