# Generated by Django 4.0.4 on 2022-05-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_remove_preguntaspage_texto_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpage',
            name='intro',
        ),
    ]
