# Generated by Django 4.0.4 on 2022-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_commentpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='conocenospage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='conocenospage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='preguntaspage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='preguntaspage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Link_a_red_social1',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='serviciospage',
            name='Link_a_red_social2',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
    ]
