# Generated by Django 4.0.4 on 2022-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_commentpage_link_a_red_social1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_5',
            field=models.CharField(default='44-34-71-43-56', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Enlace_6',
            field=models.CharField(default='55-48-33-57-29', max_length=10),
        ),
    ]
