# Generated by Django 4.0.4 on 2022-06-12 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0062_remove_commentpage_direccion_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_Red_Social_1',
            field=models.CharField(default='https://www.instagram.com/gpolias2000/?hl=es', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_Red_Social_2',
            field=models.CharField(default='https://www.facebook.com/GRUPOLIAS', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_Telefono_1',
            field=models.CharField(default='4434714356', max_length=10),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Link_a_Telefono_2',
            field=models.CharField(default='+525548335729', max_length=13),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Url_Maps',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3756.8164504686365!2d-101.19980278513917!3d19.677834686745502!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842d0d305391c24b%3A0x40f2a314c0cf0326!2sGRUPO%20LIAS!5e0!3m2!1ses!2smx!4v1650404689145!5m2!1ses!2smx', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_1',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Telefono_2',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='header',
            name='Navegación_1',
            field=models.CharField(default='Inicio', max_length=8),
        ),
        migrations.AlterField(
            model_name='header',
            name='Navegación_2',
            field=models.CharField(default='Servicios', max_length=11),
        ),
        migrations.AlterField(
            model_name='header',
            name='Navegación_3',
            field=models.CharField(default='Conócenos', max_length=11),
        ),
        migrations.AlterField(
            model_name='header',
            name='Navegación_4',
            field=models.CharField(default='Contáctanos', max_length=11),
        ),
    ]
