# Generated by Django 4.0.4 on 2022-06-12 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0063_contactpage_link_a_red_social_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='Url_Maps',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3756.8164504686365!2d-101.19980278513917!3d19.677834686745502!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842d0d305391c24b%3A0x40f2a314c0cf0326!2sGRUPO%20LIAS!5e0!3m2!1ses!2smx!4v1650404689145!5m2!1ses!2smx', help_text="Esta URL se consigue en google maps en la etiqueta compartir y en la pestaña 'Incorporar un mapa', se copia todo el link que está en el apartado 'src=' sin las comillas", max_length=500),
        ),
    ]
