# Generated by Django 4.0.4 on 2022-06-14 02:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0064_alter_contactpage_url_maps_plantilla_servicios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpage',
            old_name='thank_you_text',
            new_name='Texto_de_agradecimiento',
        ),
        migrations.AddField(
            model_name='commentpage',
            name='Imagen_de_comentarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
